---
- name: Manage Cron Entries.
  hosts: all
  gather_facts: false
  become: true


  vars:
    users_dbs:
      - /etc/passwd
      - /etc/shadow


  tasks:
    - name: Backup user database.
      ansible.builtin.cron:
        name: Backup Users.
        hour: 5
        minute: 30
        weekday: 1-5
        user: root
        job: 'tar -czf /root/user.tgz {{ users_dbs | join(" ") }}'
        cron_file: user_backup
...
