---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/local/opt/python@3.8/bin/python3
  children:
    vagrant:
      hosts:
        vagrant1:
          ansible_host: 127.0.0.1
          ansible_port: 2222
        vagrant2:
          ansible_host: 127.0.0.1
          ansible_port: 2200
        vagrant3:
          ansible_host: 127.0.0.1
          ansible_port: 2201
    web:
      hosts:
        web01:
          ansible_host: 192.168.33.10
          ansible_python_interpreter: /usr/bin/python3
