---
- name: Set up an administrative user.
  hosts: all
  become: true


  vars:
    key_file: 'files/rricaurte-contractor.pub'
    username: ansible


  tasks:
    - name: Ensure ansible user exists.
      ansible.builtin.user:
        name: '{{ username }}'
        state: present
        comment: Administrative user

    - name: Ensure ansible user accepts the SSH key.
      authorized_key:
        user: '{{ username }}'
        key: '{{ lookup("file", key_file) }}'
        state: present

    - name: Ensure the ansible user is sudoer with no password required.
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^ansible ALL\='
        line: 'ansible ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
