---
webservers:
  hosts:
    ws01.fale.io:
      ansible_port: 2222
    ws02.fale.io:
      ansible_port: 2200

database:
  hosts:
    db01.fale.io:
      ansible_port: 2201

application:
  children:
    webservers:
    database:
  vars:
    ansible_user: vagrant
    ansible_host: 127.0.0.1
