#!/usr/bin/env ansible-playbook
---
- name: Configure webserver with nginx and TLS.
  hosts: webservers
  gather_facts: false
  become: true

  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost

  tasks:
    - name: Install nginx.
      apt:
        pkg: nginx
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Create directories for TLS certificates.
      file:
        path: /etc/nginx/ssl
        state: directory
        mode: '0750'

    - name: Copy TLS key.
      copy:
        src: Files/nginx.key
        dest: '{{ key_file }}'
        owner: root
        mode: '0600'
      notify: Restart nginx.

    - name: Copy TLS certificate.
      copy:
        src: Files/nginx.crt
        dest: '{{ cert_file }}'
        mode: '0600'
      notify: Restart nginx.

    - name: Copy nginx config file.
      template:
        src: Templates/nginx.conf.j2
        dest: '{{ conf_file }}'
        mode: '0660'
      notify: Restart nginx.

    - name: Enable configuration.
      file:
        src: '{{ conf_file }}'
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart nginx.

    - name: Copy 'index.html'.
      template:
        src: Templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: '0644'

  handlers:
    - name: Restart nginx.
      service:
        name: nginx
        state: restarted
