#!/usr/bin/env ansible-playbook
---
- name: Show return value of command module.
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Capture output of id command.
      command: id -un
      register: login
    - debug:
        # var: login
        msg: 'Logged in as user {{ login.stdout }}'
